# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_flash.ui'
#
# Created: Tue Mar 15 10:33:18 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(788, 669)
        self.slot1 = QtGui.QFrame(Dialog)
        self.slot1.setGeometry(QtCore.QRect(40, 70, 131, 211))
        self.slot1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot1.setFrameShadow(QtGui.QFrame.Raised)
        self.slot1.setObjectName(_fromUtf8("slot1"))
        self.label1 = QtGui.QLabel(self.slot1)
        self.label1.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.led_esp1 = KLed(self.slot1)
        self.led_esp1.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp1.setState(KLed.Off)
        self.led_esp1.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp1.setObjectName(_fromUtf8("led_esp1"))
        self.led_msp1 = KLed(self.slot1)
        self.led_msp1.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp1.setState(KLed.Off)
        self.led_msp1.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp1.setObjectName(_fromUtf8("led_msp1"))
        self.label_esp1 = QtGui.QLabel(self.slot1)
        self.label_esp1.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp1.setObjectName(_fromUtf8("label_esp1"))
        self.label_msp1 = QtGui.QLabel(self.slot1)
        self.label_msp1.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp1.setObjectName(_fromUtf8("label_msp1"))
        self.slot2 = QtGui.QFrame(Dialog)
        self.slot2.setGeometry(QtCore.QRect(230, 70, 131, 211))
        self.slot2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot2.setFrameShadow(QtGui.QFrame.Raised)
        self.slot2.setObjectName(_fromUtf8("slot2"))
        self.label2 = QtGui.QLabel(self.slot2)
        self.label2.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.led_esp2 = KLed(self.slot2)
        self.led_esp2.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp2.setState(KLed.Off)
        self.led_esp2.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp2.setObjectName(_fromUtf8("led_esp2"))
        self.led_msp2 = KLed(self.slot2)
        self.led_msp2.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp2.setState(KLed.Off)
        self.led_msp2.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp2.setObjectName(_fromUtf8("led_msp2"))
        self.label_esp2 = QtGui.QLabel(self.slot2)
        self.label_esp2.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp2.setObjectName(_fromUtf8("label_esp2"))
        self.label_msp2 = QtGui.QLabel(self.slot2)
        self.label_msp2.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp2.setObjectName(_fromUtf8("label_msp2"))
        self.slot3 = QtGui.QFrame(Dialog)
        self.slot3.setGeometry(QtCore.QRect(420, 70, 131, 211))
        self.slot3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot3.setFrameShadow(QtGui.QFrame.Raised)
        self.slot3.setObjectName(_fromUtf8("slot3"))
        self.label3 = QtGui.QLabel(self.slot3)
        self.label3.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.led_esp3 = KLed(self.slot3)
        self.led_esp3.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp3.setState(KLed.Off)
        self.led_esp3.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp3.setObjectName(_fromUtf8("led_esp3"))
        self.led_msp3 = KLed(self.slot3)
        self.led_msp3.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp3.setState(KLed.Off)
        self.led_msp3.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp3.setObjectName(_fromUtf8("led_msp3"))
        self.label_esp3 = QtGui.QLabel(self.slot3)
        self.label_esp3.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp3.setObjectName(_fromUtf8("label_esp3"))
        self.label_msp3 = QtGui.QLabel(self.slot3)
        self.label_msp3.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp3.setObjectName(_fromUtf8("label_msp3"))
        self.slot4 = QtGui.QFrame(Dialog)
        self.slot4.setGeometry(QtCore.QRect(610, 70, 131, 211))
        self.slot4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot4.setFrameShadow(QtGui.QFrame.Raised)
        self.slot4.setObjectName(_fromUtf8("slot4"))
        self.label4 = QtGui.QLabel(self.slot4)
        self.label4.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName(_fromUtf8("label4"))
        self.led_esp4 = KLed(self.slot4)
        self.led_esp4.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp4.setState(KLed.Off)
        self.led_esp4.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp4.setObjectName(_fromUtf8("led_esp4"))
        self.led_msp4 = KLed(self.slot4)
        self.led_msp4.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp4.setState(KLed.Off)
        self.led_msp4.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp4.setObjectName(_fromUtf8("led_msp4"))
        self.label_esp4 = QtGui.QLabel(self.slot4)
        self.label_esp4.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp4.setObjectName(_fromUtf8("label_esp4"))
        self.label_msp4 = QtGui.QLabel(self.slot4)
        self.label_msp4.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp4.setObjectName(_fromUtf8("label_msp4"))
        self.start = QtGui.QPushButton(Dialog)
        self.start.setGeometry(QtCore.QRect(650, 620, 98, 27))
        self.start.setObjectName(_fromUtf8("start"))
        self.slot4_2 = QtGui.QFrame(Dialog)
        self.slot4_2.setGeometry(QtCore.QRect(40, 330, 131, 211))
        self.slot4_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot4_2.setFrameShadow(QtGui.QFrame.Raised)
        self.slot4_2.setObjectName(_fromUtf8("slot4_2"))
        self.label5 = QtGui.QLabel(self.slot4_2)
        self.label5.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label5.setAlignment(QtCore.Qt.AlignCenter)
        self.label5.setObjectName(_fromUtf8("label5"))
        self.led_esp5 = KLed(self.slot4_2)
        self.led_esp5.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp5.setState(KLed.Off)
        self.led_esp5.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp5.setObjectName(_fromUtf8("led_esp5"))
        self.led_msp5 = KLed(self.slot4_2)
        self.led_msp5.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp5.setState(KLed.Off)
        self.led_msp5.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp5.setObjectName(_fromUtf8("led_msp5"))
        self.label_esp5 = QtGui.QLabel(self.slot4_2)
        self.label_esp5.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp5.setObjectName(_fromUtf8("label_esp5"))
        self.label_msp5 = QtGui.QLabel(self.slot4_2)
        self.label_msp5.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp5.setObjectName(_fromUtf8("label_msp5"))
        self.slot6 = QtGui.QFrame(Dialog)
        self.slot6.setGeometry(QtCore.QRect(230, 330, 131, 211))
        self.slot6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot6.setFrameShadow(QtGui.QFrame.Raised)
        self.slot6.setObjectName(_fromUtf8("slot6"))
        self.label6 = QtGui.QLabel(self.slot6)
        self.label6.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label6.setAlignment(QtCore.Qt.AlignCenter)
        self.label6.setObjectName(_fromUtf8("label6"))
        self.led_esp6 = KLed(self.slot6)
        self.led_esp6.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp6.setState(KLed.Off)
        self.led_esp6.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp6.setObjectName(_fromUtf8("led_esp6"))
        self.led_msp6 = KLed(self.slot6)
        self.led_msp6.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp6.setState(KLed.Off)
        self.led_msp6.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp6.setObjectName(_fromUtf8("led_msp6"))
        self.label_esp6 = QtGui.QLabel(self.slot6)
        self.label_esp6.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp6.setObjectName(_fromUtf8("label_esp6"))
        self.label_msp6 = QtGui.QLabel(self.slot6)
        self.label_msp6.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp6.setObjectName(_fromUtf8("label_msp6"))
        self.slot7 = QtGui.QFrame(Dialog)
        self.slot7.setGeometry(QtCore.QRect(420, 330, 131, 211))
        self.slot7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot7.setFrameShadow(QtGui.QFrame.Raised)
        self.slot7.setObjectName(_fromUtf8("slot7"))
        self.label7 = QtGui.QLabel(self.slot7)
        self.label7.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label7.setAlignment(QtCore.Qt.AlignCenter)
        self.label7.setObjectName(_fromUtf8("label7"))
        self.led_esp7 = KLed(self.slot7)
        self.led_esp7.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp7.setState(KLed.Off)
        self.led_esp7.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp7.setObjectName(_fromUtf8("led_esp7"))
        self.led_msp7 = KLed(self.slot7)
        self.led_msp7.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp7.setState(KLed.Off)
        self.led_msp7.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp7.setObjectName(_fromUtf8("led_msp7"))
        self.label_esp7 = QtGui.QLabel(self.slot7)
        self.label_esp7.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp7.setObjectName(_fromUtf8("label_esp7"))
        self.label_msp7 = QtGui.QLabel(self.slot7)
        self.label_msp7.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp7.setObjectName(_fromUtf8("label_msp7"))
        self.slot8 = QtGui.QFrame(Dialog)
        self.slot8.setGeometry(QtCore.QRect(610, 330, 131, 211))
        self.slot8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.slot8.setFrameShadow(QtGui.QFrame.Raised)
        self.slot8.setObjectName(_fromUtf8("slot8"))
        self.label8 = QtGui.QLabel(self.slot8)
        self.label8.setGeometry(QtCore.QRect(40, 10, 51, 20))
        self.label8.setAlignment(QtCore.Qt.AlignCenter)
        self.label8.setObjectName(_fromUtf8("label8"))
        self.led_esp8 = KLed(self.slot8)
        self.led_esp8.setGeometry(QtCore.QRect(50, 70, 31, 31))
        self.led_esp8.setState(KLed.Off)
        self.led_esp8.setColor(QtGui.QColor(170, 170, 255))
        self.led_esp8.setObjectName(_fromUtf8("led_esp8"))
        self.led_msp8 = KLed(self.slot8)
        self.led_msp8.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.led_msp8.setState(KLed.Off)
        self.led_msp8.setColor(QtGui.QColor(170, 170, 255))
        self.led_msp8.setObjectName(_fromUtf8("led_msp8"))
        self.label_esp8 = QtGui.QLabel(self.slot8)
        self.label_esp8.setGeometry(QtCore.QRect(50, 50, 31, 17))
        self.label_esp8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_esp8.setObjectName(_fromUtf8("label_esp8"))
        self.label_msp8 = QtGui.QLabel(self.slot8)
        self.label_msp8.setGeometry(QtCore.QRect(40, 130, 51, 17))
        self.label_msp8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_msp8.setObjectName(_fromUtf8("label_msp8"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Flash Process", None))
        self.label1.setText(_translate("Dialog", "SLOT1", None))
        self.label_esp1.setText(_translate("Dialog", "ESP", None))
        self.label_msp1.setText(_translate("Dialog", "MSP", None))
        self.label2.setText(_translate("Dialog", "SLOT2", None))
        self.label_esp2.setText(_translate("Dialog", "ESP", None))
        self.label_msp2.setText(_translate("Dialog", "MSP", None))
        self.label3.setText(_translate("Dialog", "SLOT3", None))
        self.label_esp3.setText(_translate("Dialog", "ESP", None))
        self.label_msp3.setText(_translate("Dialog", "MSP", None))
        self.label4.setText(_translate("Dialog", "SLOT4", None))
        self.label_esp4.setText(_translate("Dialog", "ESP", None))
        self.label_msp4.setText(_translate("Dialog", "MSP", None))
        self.start.setText(_translate("Dialog", "Start", None))
        self.label5.setText(_translate("Dialog", "SLOT5", None))
        self.label_esp5.setText(_translate("Dialog", "ESP", None))
        self.label_msp5.setText(_translate("Dialog", "MSP", None))
        self.label6.setText(_translate("Dialog", "SLOT6", None))
        self.label_esp6.setText(_translate("Dialog", "ESP", None))
        self.label_msp6.setText(_translate("Dialog", "MSP", None))
        self.label7.setText(_translate("Dialog", "SLOT7", None))
        self.label_esp7.setText(_translate("Dialog", "ESP", None))
        self.label_msp7.setText(_translate("Dialog", "MSP", None))
        self.label8.setText(_translate("Dialog", "SLOT8", None))
        self.label_esp8.setText(_translate("Dialog", "ESP", None))
        self.label_msp8.setText(_translate("Dialog", "MSP", None))

from PyKDE4.kdeui import KLed
